version: "3"

# 声明一个名为network的networks,subnet为network的子网地址,默认网关是177.7.0.1
networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: '177.7.0.0/16'
        
volumes:
  mysql:
  
services:
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: job-log-web
    restart: always
    ports:
      - '80:80'
    depends_on:
      - server
    command: [ 'nginx', '-g', 'daemon off;' ]
    networks:
      network:
        ipv4_address: 177.7.0.11

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: job-log-server
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    links:
      - mysql
    networks:
      network:
        ipv4_address: 177.7.0.12

  mysql:
    image: mysql:8.0.32      # 如果您是 arm64 架构：如 MacOS 的 M1，请修改镜像为 image: mysql/mysql-server:8.0.21
    container_name: job-mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    ports:
      - "3306:3306"  # host物理直接映射端口为3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456' # root管理员用户密码
      MYSQL_DATABASE: 'job_log' # 初始化启动时要创建的数据库的名称
      TZ: Asia/Shanghai
    volumes:
      - mysql:/var/lib/mysql
    networks:
      network:
        ipv4_address: 177.7.0.13
